import { Animal } from '../animal';

export const ANIMALS : Animal[] = [{ name : "Abbarwa", ref : "Bestiarium S.260", countries : ["Rawindra"], areas : ["Dschungel"], rarity : 1},
{ name : "Achuticha", ref : "Im Land des Mondjaguars S.192", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Adler", ref : "Bestiarium S.260", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Berg", "Steilküste", "Wald"], rarity : 1},
{ name : "Alligator", ref : "Im Land des Mondjaguars S.199", countries : ["Feuerinseln"], areas : ["Gewässer"], rarity : 1},
{ name : "Ameisenbär", ref : "Heisses Land Buluga S.78, Im Land des Mondjaguars S.193", countries : ["Buluga", "Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Anakonda", ref : "Bestiarium S.268", countries : ["Nahuatlan"], areas : ["Gewässer"], rarity : 1},
{ name : "Anolis", ref : "Im Land des Mondjaguars S.193", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Antilope", ref : "Bestiarium S.39", countries : ["Buluga", "Ikenga Becken", "Mokattam", "Urruti", "Nahuatlan", "Aran", "Minangpahit", "Rawindra", "Tegarische Steppe", "Feuerinseln", "Serendib"], areas : ["Steppe", "Savanne", "Berg"], rarity : 1},
{ name : "Arakane", ref : "Bestiarium S.71", countries : ["Ikenga Becken", "Nahuatlan", "Minangpahit", "Rawindra", "Feuerinseln"], areas : ["Dschungel"], rarity : 1},
{ name : "Baumläuferin", ref : "Bestiarium S.283", countries : ["Medjis", "Moravod", "Tegarische Steppe"], areas : ["Wald", "Urwald"], rarity : 1},
{ name : "Bedwenbär", ref : "Bestiarium S.43", countries : ["Alba", "Clanngadarn", "Fuardain", "Ywerddon"], areas : ["Wald"], rarity : 1},
{ name : "Bergaffe", ref : "Im Bann der Todesechsen S.109", countries : ["Rawindra"], areas : ["Berg"], rarity : 1},
{ name : "Bergdachs", ref : "Im Land des Mondjaguars S.190", countries : ["Nahuatlan"], areas : ["Höhle", "Berg"], rarity : 1},
{ name : "Berglöwe", ref : "Bestiarium S.167", countries : ["Eschar", "Küstenstaaten", "Nahuatlan", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Berg"], rarity : 1},
{ name : "Bergtroll", ref : "Bestiarium S.293", countries : ["Medjis", "Moravod", "Waeland", "Alba", "Clanngadarn", "Fuardain", "Ywerddon"], areas : ["Berg"], rarity : 1},
{ name : "Bisamschwein", ref : "Im Land des Mondjaguars S.193", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Blattschneiderameise", ref : "Im Land des Mondjaguars S.187", countries : ["Nahuatlan"], areas : ["Ebene", "Hochebene"], rarity : 1},
{ name : "Blitzfalter", ref : "Bestiarium S.156", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Höhle"], rarity : 1},
{ name : "Blutegel", ref : "Bestiarium S.362", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Sumpf", "Gewässer"], rarity : 1},
{ name : "Boa", ref : "Bestiarium S.268", countries : ["Nahuatlan"], areas : ["Wald", "Ruine"], rarity : 1},
{ name : "Braunbär", ref : "Bestiarium S.43", countries : ["Küstenstaaten", "Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Inseln unter dem Westwind", "Pfortenarchipel", "Valian"], areas : ["Wald", "Berg"], rarity : 1},
{ name : "Brüllaffe", ref : "Im Land des Mondjaguars S.192", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Buschratte", ref : "Im Land des Mondjaguars S.190", countries : ["Nahuatlan"], areas : ["Berg"], rarity : 1},
{ name : "Cantil", ref : "Im Land des Mondjaguars S.186, Bestiarium S.265", countries : ["Nahuatlan"], areas : ["Gewässer", "Sumpf"], rarity : 1},
{ name : "Chapique", ref : "Im Land des Mondjaguars S.187", countries : ["Nahuatlan"], areas : ["Wald", "Dschungel", "Urwald"], rarity : 1},
{ name : "Chimachima", ref : "Im Land des Mondjaguars S.178", countries : ["Nahuatlan"], areas : ["Stadt"], rarity : 1},
{ name : "Chiroax", ref : "Im Land des Mondjaguars S.194", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Coruum", ref : "Bestiarium S.183", countries : ["Aran", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe"], areas : ["Ebene", "Steppe", "Savanne"], rarity : 1},
{ name : "Coyotin", ref : "Im Land des Mondjaguars S.178", countries : ["Nahuatlan"], areas : ["Ebene", "Steppe", "Savanne", "Wald", "Küste"], rarity : 1},
{ name : "Cullobo-Fuchs", ref : "Im Land des Mondjaguars S.190", countries : ["Nahuatlan"], areas : ["Berg"], rarity : 1},
{ name : "Die-bei-der-ein-tapferer-Mann-nach-Luft-schnappt", ref : "Heisses Land Buluga S.79", countries : ["Buluga"], areas : ["Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Dschungeläffchen", ref : "Bestiarium S.35", countries : ["Ikenga Becken", "Nahuatlan", "Minangpahit", "Feuerinseln"], areas : ["Dschungel"], rarity : 1},
{ name : "Dschungelhuhn", ref : "Im Land des Mondjaguars S.193", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Dunkelwolf", ref : "Bestiarium S.359", countries : ["Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Wald", "Berg"], rarity : 1},
{ name : "Eisbär", ref : "Bestiarium S.43", countries : ["Waeland", "Fuardain"], areas : ["Küste"], rarity : 1},
{ name : "Eistroll", ref : "Bestiarium S.296", countries : ["Waeland", "Clanngadarn", "Fuardain"], areas : ["Berg"], rarity : 1},
{ name : "Elch", ref : "Bestiarium S.144", countries : ["Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Clanngadarn", "Fuardain", "Ywerddon"], areas : ["Steppe", "Ebene", "Wald", "Sumpf"], rarity : 1},
{ name : "Elefant", ref : "Bestiarium S.52", countries : ["Buluga", "Ikenga Becken", "Mokattam", "Urruti", "Nahuatlan", "Minangpahit", "Rawindra", "Feuerinseln", "Serendib"], areas : ["Dschungel", "Savanne"], rarity : 1},
{ name : "Elster", ref : "Bestiarium S.249", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["überall ausser in Wüste", "Steppe und Eisöde"], rarity : 1},
{ name : "Emu", ref : "Heisses Land Buluga S.78, Bestiarium S.185", countries : ["Buluga", "Minangpahit", "Rawindra"], areas : ["Ebene", "Hochebene"], rarity : 1},
{ name : "Erdferkel", ref : "Heisses Land Buluga S.78", countries : ["Buluga"], areas : ["Steppe", "Savanne", "Ebene"], rarity : 1},
{ name : "Erdmännchen", ref : "Bestiarium S.273", countries : ["Buluga", "Eschar", "Küstenstaaten", "Mokattam", "Urruti"], areas : ["Savanne", "Steppe"], rarity : 1},
{ name : "Esel", ref : "Bestiarium S.242", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Ebene", "Savanne", "Steppe", "Berg"], rarity : 1},
{ name : "Falke", ref : "Bestiarium S.129", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Berg", "Steilküste", "Wald", "Urwald", "Ebene", "Steppe"], rarity : 1},
{ name : "Färberfrosch", ref : "Bestiarium S.186", countries : ["Ikenga Becken", "Nahuatlan", "Feuerinseln"], areas : ["Dschungel"], rarity : 1},
{ name : "Fauchschabe", ref : "Bestiarium S.157", countries : ["Minangpahit", "Rawindra"], areas : ["Ebene", "Steppe", "Savanne", "Wald", "Urwald", "Dschungel", "Stadt"], rarity : 1},
{ name : "Faultier", ref : "Im Land des Mondjaguars S.194", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Federechse", ref : "Bestiarium S.73", countries : ["Buluga", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "KanThaiPan", "Minangpahit", "Rawindra", "Chryseia", "Erainn", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Wald", "Gebirgstal"], rarity : 1},
{ name : "Federschlange", ref : "Im Land des Mondjaguars S.194", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Federspinne", ref : "Bestiarium S.284", countries : ["Nahuatlan", "Feuerinseln"], areas : ["Dschungel"], rarity : 1},
{ name : "Felsnatter", ref : "Im Bann der Todesechsen S.113", countries : ["Rawindra"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Fetchamäleon", ref : "Bestiarium S.73", countries : ["Ikenga Becken", "Nahuatlan", "Minangpahit", "Rawindra", "Feuerinseln"], areas : ["Dschungel"], rarity : 1},
{ name : "Floh", ref : "Bestiarium S.159", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Ebene", "Hochebene", "Steppe", "Savanne", "Wald", "Urwald", "Regenwald", "Berg", "Stadt"], rarity : 1},
{ name : "Flughörnchen", ref : "Heisses Land Buluga S.78", countries : ["Buluga"], areas : ["Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Flußpferd", ref : "Bestiarium S.53", countries : ["Buluga", "Ikenga Becken", "Urruti", "Minangpahit", "Rawindra", "Serendib"], areas : ["Gewässer"], rarity : 1},
{ name : "Frettchen", ref : "Bestiarium S.190", countries : ["Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Ebene", "Steppe", "Wald", "Gewässer", "Stadt"], rarity : 1},
{ name : "Gans", ref : "Bestiarium S.340", countries : ["Medjis", "Moravod", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Gewässer", "Sumpf"], rarity : 1},
{ name : "Gazelle", ref : "Bestiarium S.40", countries : ["Buluga", "Ikenga Becken", "Mokattam", "Urruti", "Nahuatlan", "Aran", "Minangpahit", "Rawindra", "Tegarische Steppe", "Feuerinseln", "Serendib"], areas : ["Steppe", "Savanne", "Berg"], rarity : 1},
{ name : "Gecko", ref : "Heisses Land Buluga S.78", countries : ["Buluga"], areas : ["Wald", "Dschungel", "Urwald", "Regenwald", "Steppe", "Savanne", "Wüste"], rarity : 1},
{ name : "Geier", ref : "Bestiarium S.130", countries : ["Buluga", "Eschar", "Küstenstaaten", "Mokattam", "Nahuatlan", "Aran", "KanThaiPan", "Tegarische Steppe", "Chryseia", "Erainn"], areas : ["Berg", "Savanne", "Steppe"], rarity : 1},
{ name : "Geieradler", ref : "Bestiarium S.131", countries : ["Nahuatlan"], areas : ["Berg", "Savanne", "Steppe"], rarity : 1},
{ name : "Gepard", ref : "Bestiarium S.167", countries : ["Aran", "Rawindra", "Tegarische Steppe"], areas : ["Savanne", "Steppe"], rarity : 1},
{ name : "Gladiatorspinne", ref : "Bestiarium S.285", countries : ["Buluga", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Chryseia", "Erainn", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Wald", "Ebene", "Sumpf"], rarity : 1},
{ name : "Gleitwal", ref : "Bestiarium S.364", countries : ["Waeland", "Fuardain"], areas : ["Ebene", "Steppe"], rarity : 1},
{ name : "Gnu", ref : "Bestiarium S.41", countries : ["Buluga", "Mokattam", "Urruti", "Nahuatlan", "Aran", "Rawindra", "Tegarische Steppe", "Serendib"], areas : ["Steppe", "Savanne"], rarity : 1},
{ name : "Goldkopfschlange", ref : "Heisses Land Buluga S.79", countries : ["Buluga"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Gorilla", ref : "Bestiarium S.36", countries : ["Ikenga Becken", "Nahuatlan", "Minangpahit", "Feuerinseln"], areas : ["Dschungel", "Bergwald"], rarity : 1},
{ name : "Grasschlange", ref : "Heisses Land Buluga S.79", countries : ["Buluga"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Gürteltier", ref : "Im Land des Mondjaguars S.196", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Haubenadler", ref : "Bestiarium S.127", countries : ["Buluga", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Wald"], rarity : 1},
{ name : "Heeresameise", ref : "Bestiarium S.160", countries : ["Buluga", "Urruti", "Nahuatlan"], areas : ["Ebene", "Savanne", "Steppe"], rarity : 1},
{ name : "Helmkasuar", ref : "Heisses Land Buluga S.82", countries : ["Buluga"], areas : ["Wald"], rarity : 1},
{ name : "Heuschrecke", ref : "Heisses Land Buluga S.78", countries : ["Buluga"], areas : ["Ebene", "Steppe", "Savanne"], rarity : 1},
{ name : "Hirsch", ref : "Bestiarium S.145", countries : ["Buluga", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Inseln unter dem Westwind", "Pfortenarchipel", "Valian"], areas : ["Wald"], rarity : 1},
{ name : "Hochrabe", ref : "Bestiarium S.250", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Berg"], rarity : 1},
{ name : "Höhlenbär", ref : "Bestiarium S.44", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Berg", "Hochebene"], rarity : 1},
{ name : "Honigameise", ref : "Im Land des Mondjaguars S.187", countries : ["Nahuatlan"], areas : ["Steppe", "Berg"], rarity : 1},
{ name : "Honigdachs", ref : "Bestiarium S.192", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti"], areas : ["Berg"], rarity : 1},
{ name : "Hornfrosch", ref : "Im Land des Mondjaguars S.195", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Hornisse", ref : "Heisses Land Buluga S.78", countries : ["Buluga"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Hornviper", ref : "Heisses Land Buluga S.79", countries : ["Buluga"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Hügeltroll", ref : "Bestiarium S.305", countries : ["Medjis", "Moravod", "Waeland", "Alba", "Clanngadarn", "Fuardain", "Ywerddon"], areas : ["Berg", "Hochebene"], rarity : 1},
{ name : "Hulman", ref : "Im Bann der Todesechsen S.109", countries : ["Rawindra"], areas : ["Stadt", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Hünensau", ref : "Bestiarium S.280", countries : ["Alba", "Clanngadarn", "Fuardain", "Ywerddon"], areas : ["Wald"], rarity : 1},
{ name : "Hyäne", ref : "Heisses Land Buluga S.78", countries : ["Buluga"], areas : ["Ebene", "Steppe", "Savanne"], rarity : 1},
{ name : "Ichneumon", ref : "Bestiarium S.274", countries : ["Eschar", "Küstenstaaten", "Minangpahit", "Rawindra", "Valian"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald", "Berg", "Hochebene", "Savanne", "Wüste"], rarity : 1},
{ name : "Insekten", ref : "Bestiarium S.152 ff.", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald", "Berg", "Hochebene", "Savanne", "Wüste"], rarity : 1},
{ name : "Ixtanx", ref : "Im Land des Mondjaguars S.186", countries : ["Nahuatlan"], areas : ["Sumpfe"], rarity : 1},
{ name : "Jaguar", ref : "Im Land des Mondjaguars S.196", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Jaguarameise", ref : "Im Land des Mondjaguars S.192", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "JinSche", ref : "Unter dem Schirm des Jadekaisers S.263", countries : ["KanThaiPan"], areas : ["Wald"], rarity : 1},
{ name : "Kamel", ref : "Bestiarium S.242", countries : ["Buluga", "Eschar", "Küstenstaaten", "Mokattam", "Nahuatlan", "Aran", "Tegarische Steppe", "Feuerinseln", "Serendib", "Valian"], areas : ["Wüste"], rarity : 1},
{ name : "Känguruh", ref : "Heisses Land Buluga S.83", countries : ["Buluga"], areas : ["Savanne"], rarity : 1},
{ name : "Kapuziner", ref : "Im Land des Mondjaguars S.192", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Killerbiene", ref : "Heisses Land Buluga S.78", countries : ["Buluga"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "KiSchan", ref : "Unter dem Schirm des Jadekaisers S.266", countries : ["KanThaiPan"], areas : ["Wald"], rarity : 1},
{ name : "Klapperschlange", ref : "Im Land des Mondjaguars S.188", countries : ["Nahuatlan"], areas : ["Steppe", "Berg"], rarity : 1},
{ name : "Kondor", ref : "Im Land des Mondjaguars S.191", countries : ["Nahuatlan"], areas : ["Berg"], rarity : 1},
{ name : "Königskobra", ref : "Bestiarium S.266", countries : ["Minangpahit", "Rawindra"], areas : ["Dschungel"], rarity : 1},
{ name : "Koyala", ref : "Im Bann der Todesechsen S.115", countries : ["Rawindra"], areas : ["Stadt", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Krall", ref : "Bestiarium S.187", countries : ["Buluga", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Sumpf"], rarity : 1},
{ name : "Krallenfuß", ref : "Im Land des Mondjaguars S.188", countries : ["Nahuatlan"], areas : ["Sumpf", "Dschungel"], rarity : 1},
{ name : "Kravyad", ref : "Bestiarium S.260", countries : ["Rawindra"], areas : ["Dschungel"], rarity : 1},
{ name : "Kreuzotter", ref : "Bestiarium S.266", countries : ["Moravod", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Ebene", "Steppe", "Wald", "Urwald", "Berg", "Hochebene", "Savanne"], rarity : 1},
{ name : "Krokodil", ref : "Bestiarium S.176", countries : ["Buluga", "Eschar", "Ikenga Becken", "Mokattam", "Urruti", "Nahuatlan", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Chryseia", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Gewässer"], rarity : 1},
{ name : "Krötenechse", ref : "Im Land des Mondjaguars S.188", countries : ["Nahuatlan"], areas : ["Steppe"], rarity : 1},
{ name : "Lachhabicht", ref : "Im Land des Mondjaguars S.188", countries : ["Nahuatlan"], areas : ["Ebene", "Hochebene"], rarity : 1},
{ name : "Lagunenwurm", ref : "Im Land des Mondjaguars S.184", countries : ["Nahuatlan"], areas : ["Küste"], rarity : 1},
{ name : "Langzüngler", ref : "Im Land des Mondjaguars S.194	", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Leopard/Jaguar", ref : "Bestiarium S.169", countries : ["Buluga", "Ikenga Becken", "Mokattam", "Urruti", "Nahuatlan", "Minangpahit", "Rawindra", "Feuerinseln", "Serendib"], areas : ["Dschungel", "Savanne"], rarity : 1},
{ name : "Löwe", ref : "Bestiarium S.170	", countries : ["Buluga", "Eschar", "Küstenstaaten", "Mokattam", "Nahuatlan", "Aran", "Tegarische Steppe", "Serendib", "Valian"], areas : ["Steppe", "Savanne", "Wald"], rarity : 1},
{ name : "Löwenotter", ref : "Heisses Land Buluga S.79	", countries : ["Buluga"], areas : ["Wald", "Dschungel", "Urwald", "Ebene", "Steppe", "Savanne", "Regenwald"], rarity : 1},
{ name : "Luchs", ref : "Bestiarium S.171	", countries : ["Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Wald", "Berg"], rarity : 1},
{ name : "Makara", ref : "Bestiarium S.261	", countries : ["Rawindra"], areas : ["Dschungel"], rarity : 1},
{ name : "Mammut", ref : "Bestiarium S.54", countries : ["Waeland"], areas : ["Ebene", "Wald"], rarity : 1},
{ name : "Mäuse", ref : "Bestiarium S.222	", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Stadt", "Wald", "Dschungel", "Urwald", "Regenwald", "Bergwald"], rarity : 1},
{ name : "Miko", ref : "Unter dem Schirm des Jadekaisers S.269		", countries : ["KanThaiPan"], areas : ["Bergwald"], rarity : 1},
{ name : "Misure", ref : "Bestiarium S.145        ", countries : ["KanThaiPan", "Medjis", "Waeland"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald", "Berg", "Hochebene", "Savanne", "Wüste"], rarity : 1},
{ name : "Moa", ref : "Bestiarium S.184	", countries : ["Buluga", "Urruti"], areas : ["Stadt", "Savanne"], rarity : 1},
{ name : "Moorlemming", ref : "Bestiarium S.223	", countries : ["Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Clanngadarn", "Fuardain", "Ywerddon"], areas : ["Sumpf"], rarity : 1},
{ name : "Mörderpinguin", ref : "Die Krieger des Nordens S.102	", countries : ["Waeland"], areas : ["Küste", "Ebene"], rarity : 1},
{ name : "Mungo", ref : "Im Bann der Todesechsen S.112	", countries : ["Rawindra"], areas : ["Stadt", "Dschungel"], rarity : 1},
{ name : "Mussurana", ref : "Bestiarium S.266	", countries : ["Minangpahit", "Rawindra"], areas : ["Dschungel"], rarity : 1},
{ name : "Nandu", ref : "Im Land des Mondjaguars S.188	", countries : ["Nahuatlan"], areas : ["Hochebene"], rarity : 1},
{ name : "Nasenbär", ref : "Im Land des Mondjaguars S.196	", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Nashorn", ref : "Bestiarium S.54", countries : ["Buluga", "Ikenga Becken", "Mokattam", "Urruti", "Nahuatlan", "Minangpahit", "Rawindra", "Feuerinseln", "Serendib"], areas : ["Dschungel", "Savanne"], rarity : 1},
{ name : "Nudisschrecke", ref : "Bestiarium S.161	", countries : ["Buluga", "Eschar", "Ikenga Becken", "Mokattam", "Urruti"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald", "Berg", "Hochebene", "Savanne", "Wüste"], rarity : 1},
{ name : "Otter", ref : "Bestiarium S.194	", countries : ["Buluga", "Eschar (Kairawan & Elhaddar)", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Gewässer", "Küste"], rarity : 1},
{ name : "Ozelot", ref : "Im Land des Mondjaguars S.196	", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Papagei", ref : "Bestiarium S.340	", countries : ["Buluga", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Minangpahit", "Rawindra", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Dschungel", "Savanne", "Ebene"], rarity : 1},
{ name : "Pestkröte", ref : "Bestiarium S.188	", countries : ["Rawindra"], areas : ["Wald", "Gewässer. Urwald", "Regenwald", "Dschungel", "Sumpf"], rarity : 1},
{ name : "Pferd", ref : "Bestiarium S.243	", countries : ["Buluga", "Eschar", "Ikenga Becken" ,"Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Stadt", "Steppe", "Ebene", "Küste"], rarity : 1},
{ name : "Pudu", ref : "Im Land des Mondjaguars S.191	", countries : ["Nahuatlan"], areas : ["Berg"], rarity : 1},
{ name : "Puffotter", ref : "Bestiarium S.266	", countries : ["Buluga", "Ikenga Becken", "Mokattam", "Urruti"], areas : ["Dschungel"], rarity : 1},
{ name : "Puma", ref : "Im Land des Mondjaguars S.191	", countries : ["Nahuatlan"], areas : ["Berg"], rarity : 1},
{ name : "Python", ref : "Bestiarium S.268, Heisses Land Buluga S.79", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti"], areas : ["Dschungel", "Wald", "Ruine"], rarity : 1},
{ name : "Rabe", ref : "Bestiarium S.250	", countries : ["Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Berg", "Wald", "Stadt", "Urwald"], rarity : 1},
{ name : "Rasselotter", ref : "Bestiarium S.267	", countries : ["Eschar", "Mokattam", "Nahuatlan", "Aran", "KanThaiPan", "Tegarische Steppe"], areas : ["Wüste", "Steppe"], rarity : 1},
{ name : "Ratte", ref : "Bestiarium S.224	", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Stadt", "Wald", "Dschungel", "Urwald", "Regenwald", "Bergwald"], rarity : 1},
{ name : "Regimentkrabbe", ref : "Bestiarium S.178	", countries : ["Buluga", "Urruti", "Minangpahit"], areas : ["Küste"], rarity : 1},
{ name : "Renntier", ref : "Bestiarium S.145	", countries : ["Waeland"], areas : ["Wald", "Ebene"], rarity : 1},
{ name : "Riesenadler", ref : "Bestiarium S.128	", countries : ["Eschar", "Küstenstaaten", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Berg"], rarity : 1},
{ name : "Riesengötteranruferin", ref : "Heisses Land Buluga S.78	", countries : ["Buluga"], areas : ["Regenwald"], rarity : 1},
{ name : "Riesenwespe", ref : "Im Land des Mondjaguars S.198	", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Riesenzecke", ref : "Bestiarium S.287	", countries : ["Buluga", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Wald", "Höhle"], rarity : 1},
{ name : "Rind", ref : "Bestiarium S.253	", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Stadt", "Ebene", "Wald", "Steppe", "Savanne"], rarity : 1},
{ name : "Säbelzahntiger", ref : "Bestiarium S.171	", countries : ["Buluga", "Ikenga Becken", "Mokattam", "Urruti", "Tegarische Steppe"], areas : ["Steppe", "Hochland", "Savanne"], rarity : 1},
{ name : "Saimiri", ref : "Im Land des Mondjaguars S.179", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Salzwasserkrokodil", ref : "Bestiarium S.177	", countries : ["Buluga", "Eschar", "Ikenga Becken", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Minangpahit", "Rawindra", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Küste"], rarity : 1},
{ name : "Schakal", ref : "Heisses Land Buluga S.78	", countries : ["Buluga"], areas : ["Savanne", "Steppe"], rarity : 1},
{ name : "Schlangenadler", ref : "Bestiarium S.128	", countries : ["Eschar", "Nahuatlan", "Aran"], areas : ["Wüste"], rarity : 1},
{ name : "Schnappschildkröte", ref : "Bestiarium S.263	", countries : ["Ikenga Becken", "Nahuatlan", "Feuerinseln"], areas : ["Sumpf", "Gewässer"], rarity : 1},
{ name : "Schneewolf", ref : "Bestiarium S.360	", countries : ["Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Clanngadarn", "Fuardain", "Ywerddon"], areas : ["Berg"], rarity : 1},
{ name : "Schwarze Manga", ref : "Heisses Land Buluga S.79", countries : ["Buluga"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Schwarzer Schwan", ref : "Heisses Land Buluga S.78", countries : ["Buluga"], areas : ["Gewässer"], rarity : 1},
{ name : "Seidenspinne", ref : "Im Land des Mondjaguars S.197	", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Silberdachs", ref : "Im Land des Mondjaguars S.189	", countries : ["Nahuatlan"], areas : ["Ebene", "Hochebene"], rarity : 1},
{ name : "Skorpion", ref : "Bestiarium S.288	", countries : ["Buluga", "Eschar", "Mokattam", "Nahuatlan", "Aran", "KanThaiPan", "Serendib"], areas : ["Wüste", "Steppe"], rarity : 1},
{ name : "Skunk", ref : "Im Land des Mondjaguars S.189, Bestiarium S.195        ", countries : ["Nahuatlan"], areas : ["Steppe"], rarity : 1},
{ name : "Sonnentruthahn", ref : "Im Land des Mondjaguars S.180	", countries : ["Nahuatlan"], areas : ["Wald", "Stadt"], rarity : 1},
{ name : "Speikobra", ref : "Bestiarium S.269	", countries : ["Buluga", "Urruti", "Minangpahit", "Rawindra"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Speispinne", ref : "Bestiarium S.289	", countries : ["Buluga", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Chryseia", "Erainn", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Wald", "Ebene", "Savanne"], rarity : 1},
{ name : "Sperber", ref : "Bestiarium S.132	", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit" ,"Moravod" ,"Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Wald", "Savanne", "Steppe"], rarity : 1},
{ name : "Spießbock", ref : "Heisses Land Buluga S.78", countries : ["Buluga"], areas : ["Ebene", "Savanne", "Steppe"], rarity : 1},
{ name : "Springratte", ref : "Heisses Land Buluga S.83", countries : ["Buluga"], areas : ["Savanne"], rarity : 1},
{ name : "Stachelratte", ref : "Im Land des Mondjaguars S.198", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Steppenbüffel", ref : "Bestiarium S.252", countries : ["Moravod", "Tegarische Steppe", "Waeland", "Clanngadarn", "Fuardain"], areas : ["Ebene"], rarity : 1},
{ name : "Strandkrabbe", ref : "Im Land des Mondjaguars S.185", countries : ["Nahuatlan"], areas : ["Küste"], rarity : 1},
{ name : "Strauß", ref : "Bestiarium S.185", countries : ["Buluga", "Mokattam", "Urruti"], areas : ["Ebene", "Hochland"], rarity : 1},
{ name : "Sumpfkobold", ref : "Die Krieger des Nordens S.99 	", countries : ["Waeland", "Moravod"], areas : ["Sumpf", "Wald", "Gewässer"], rarity : 1},
{ name : "Sumpfotter", ref : "Bestiarium S.194", countries : ["Buluga", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Sumpf"], rarity : 1},
{ name : "Tapir", ref : "Im Land des Mondjaguars S.198", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Tapir, großer", ref : "Im Land des Mondjaguars S.199", countries : ["Feuerinseln"], areas : ["Dschungel"], rarity : 1},
{ name : "Taschenfrosch", ref : "Bestiarium S.186", countries : ["Ikenga Becken", "Urruti", "Minangpahit", "Rawindra"], areas : ["Dschungel"], rarity : 1},
{ name : "Tayra", ref : "Im Land des Mondjaguars S.180", countries : ["Nahuatlan"], areas : ["Ebene", "Steppe", "Savanne", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Termite", ref : "Heisses Land Buluga S.79", countries : ["Buluga"], areas : ["Wald", "Dschungel", "Urwald", "Regenwald", "Savanne"], rarity : 1},
{ name : "Tiger", ref : "Bestiarium S.173", countries : ["KanThaiPan", "Medjis", "Minangpahit", "Rawindra"], areas : ["Dschungel", "Urwald"], rarity : 1},
{ name : "Tigerpferd", ref : "Bestiarium S.246", countries : ["Buluga", "Urruti"], areas : ["Steppe", "Savanne", "Hochland"], rarity : 1},
{ name : "Töpfervogel", ref : "Im Land des Mondjaguars S.180", countries : ["Nahuatlan"], areas : ["Stadt"], rarity : 1},
{ name : "Trivajra", ref : "Bestiarium S.262", countries : ["Rawindra"], areas : ["Dschungel"], rarity : 1},
{ name : "Tupfenbuschkatze", ref : "Heisses Land Buluga S.79", countries : ["Buluga"], areas : ["Ebene", "Steppe", "Savanne", "Wald", "Dschungel"], rarity : 1},
{ name : "Uhu", ref : "Bestiarium S.85", countries : ["KanThaiPan", "Medjis", "Moravod", "Tegarische Steppe"], areas : ["Wald"], rarity : 1},
{ name : "Vielfraß", ref : "Im Land des Mondjaguars S.198", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Waldkauz", ref : "Bestiarium S.86", countries : ["KanThaiPan", "Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Wald"], rarity : 1},
{ name : "Waldkobold", ref : "Die Krieger des Nordens S.100", countries : ["Waeland"], areas : ["Wald"], rarity : 1},
{ name : "Waldochse", ref : "Bestiarium S.254", countries : ["Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Inseln unter dem Westwind", "Pfortenarchipel", "Valian"], areas : ["Wald", "Savanne"], rarity : 1},
{ name : "Waran", ref : "Heisses Land Buluga S.79", countries : ["Buluga"], areas : ["Savanne", "Steppe", "Dschungel", "Wald"], rarity : 1},
{ name : "Waschbär", ref : "Bestiarium S.44", countries : ["Küstenstaaten", "Moravod", "Alba", "Erainn"], areas : ["Wald"], rarity : 1},
{ name : "Wasserbüffel", ref : "Bestiarium S.252", countries : ["KanThaiPan", "Minangpahit"], areas : ["Sumpf", "Gewässer"], rarity : 1},
{ name : "Weißrüsselbär", ref : "Im Land des Mondjaguars S.198", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Wieselkatze", ref : "Im Land des Mondjaguars S.181", countries : ["Nahuatlan"], areas : ["Stadt", "Gewässer", "Küste", "Dschungel", "Regenwald"], rarity : 1},
{ name : "Wildkatze", ref : "Bestiarium S.174", countries : ["Aran", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Wald", "Savanne", "Ebene"], rarity : 1},
{ name : "Wildschwein", ref : "Bestiarium S.281", countries : ["Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Wald"], rarity : 1},
{ name : "Wolf", ref : "Bestiarium S.361", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Berg", "Wald", "Ebene", "Steppe"], rarity : 1},
{ name : "Wolfsspinne", ref : "Bestiarium S.290", countries : ["Buluga", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Wald", "Dschungel"], rarity : 1},
{ name : "Wollbeutelratte", ref : "Im Land des Mondjaguars S.198", countries : ["Nahuatlan"], areas : ["Dschungel"], rarity : 1},
{ name : "Wulfsteader", ref : "Bestiarium S.151", countries : ["Alba", "Clanngadarn", "Erainn"], areas : ["Stadt"], rarity : 1},
{ name : "Wüstenratte", ref : "Bestiarium S.226", countries : ["Buluga", "Eschar", "Mokattam", "Urruti", "Aran"], areas : ["Wüste", "Steppe"], rarity : 1},
{ name : "Yak", ref : "Bestiarium S.254", countries : ["Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland"], areas : ["Berg"], rarity : 1},
{ name : "Yapok", ref : "Im Land des Mondjaguars S.187", countries : ["Nahuatlan"], areas : ["Gewässer"], rarity : 1},
{ name : "Zecke", ref : "Heisses Land Buluga S.79", countries : ["Buluga"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Zikade", ref : "Heisses Land Buluga S.79", countries : ["Buluga", "Eschar", "Ikenga Becken", "Küstenstaaten", "Mokattam", "Urruti", "Nahuatlan", "Aran", "KanThaiPan", "Medjis", "Minangpahit", "Moravod", "Rawindra", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon", "Feuerinseln", "Inseln unter dem Westwind", "Pfortenarchipel", "Serendib", "Valian"], areas : ["Sumpf", "Wald", "Bergwald", "Urwald", "Regenwald", "Dschungel", "Savanne", "Ebene"], rarity : 1},
{ name : "Znarfa-Spinne", ref : "Im Bann der Todesechsen S.116", countries : ["Serendib"], areas : ["Ebene", "Steppe", "Wald", "Dschungel", "Urwald", "Regenwald"], rarity : 1},
{ name : "Zorilla", ref : "Bestiarium S.195", countries : ["Nahuatlan", "Tegarische Steppe"], areas : ["Steppe"], rarity : 1},
{ name : "Zwergspecht", ref : "Bestiarium S.342", countries : ["Medjis", "Moravod", "Tegarische Steppe", "Waeland", "Alba", "Chryseia", "Clanngadarn", "Erainn", "Fuardain", "Ywerddon"], areas : ["Berg"], rarity : 1}];
